GCLOUD_LOCATION: "us-central1"
GCLOUD_PROJECT_ID: "st-assignment3"
BACKEND_URL: "http://localhost:8081/chat"
STORAGE_BUCKET_NAME: "personal-expense-assistant-receipts-vsb"
DB_COLLECTION_NAME: "personal-expense-assistant-receipts"